export const APPROVE_REQUEST = "APPROVE_REQUEST";
export const LIST_REQUESTS = "LIST_REQUESTS";
export const ADD_USER = "ADD_USER";
export const DELETE_REQUEST = "DELETE_REQUEST";
export const DISAPPROVE_REQUEST = "DISAPPROVE_REQUEST";
export const BLOCK_REQUEST = "BLOCK_REQUEST";
export const UNBLOCK_REQUEST = "UNBLOCK_REQUEST";

